# Generated by Django 4.1.1 on 2023-12-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tab',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tabtype',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=30, null=True),
        ),
    ]
