# Generated by Django 4.1.1 on 2024-11-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchinfo',
            old_name='red_card_oponent',
            new_name='corner',
        ),
        migrations.RenameField(
            model_name='matchinfo',
            old_name='substitution_oponent',
            new_name='corner_opponent',
        ),
        migrations.RenameField(
            model_name='matchinfo',
            old_name='yellow_card_oponent',
            new_name='red_card_opponent',
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='substitution_opponent',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='yellow_card_opponent',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
