# Generated by Django 4.1.1 on 2023-04-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_action_events_event'),
        ('api', '0003_websocket'),
        ('api', '0004_note'),
    ]

    operations = [
    ]
