# Generated by Django 4.1.1 on 2023-04-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20230402_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='auto_create',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
