# Generated by Django 4.1.1 on 2023-05-28 08:40

import api.match_modes
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20230402_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mode',
            field=enumfields.fields.EnumField(default='LIVE', enum=api.match_modes.Match_modes, max_length=10),
        ),
    ]
