# Generated by Django 4.1.1 on 2022-10-04 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='team',
        ),
        migrations.AddField(
            model_name='action',
            name='color',
            field=models.CharField(default='blue', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
