# Generated by Django 4.1.1 on 2024-11-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_action_team_alter_action_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
            preserve_default=False,
        ),
    ]
