# Generated by Django 4.1.1 on 2024-11-24 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_alter_action_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='delay',
        ),
        migrations.AddField(
            model_name='event',
            name='delay_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TemporalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ACTIVE', max_length=30, null=True)),
                ('start', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('delay_start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('delay_end', models.IntegerField(null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.action')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
