# Generated by Django 4.1.1 on 2022-10-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_match_created_at_match_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='media',
            field=models.URLField(default='http:s3.es'),
            preserve_default=False,
        ),
    ]
