# Generated by Django 4.1.1 on 2022-10-14 14:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_match_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=['2022'], size=None),
            preserve_default=False,
        ),
    ]
