# Generated by Django 4.1.1 on 2024-11-24 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_remove_event_delay_event_delay_start_event_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
