# Generated by Django 4.1.1 on 2022-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_action_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished_at',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='started_at',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
