# Generated by Django 4.1.1 on 2024-12-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_lineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='second_media',
            field=models.URLField(blank=True, null=True),
        ),
    ]
