# Generated by Django 4.1.1 on 2022-11-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_match_media_alter_match_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
