# Generated by Django 4.1.1 on 2023-01-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_tab_action_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tab'),
        ),
    ]
