# Generated by Django 4.1.1 on 2022-11-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='finished_at',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='media',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='started_at',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='timeline',
            field=models.URLField(blank=True, null=True),
        ),
    ]
