# Generated by Django 4.1.1 on 2023-01-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_action_created_at_remove_action_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='event',
            name='disabled',
        ),
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
