# Generated by Django 4.1.1 on 2023-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_tabtype_tab_created_at_delete_event_tab_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
