# Generated by Django 4.1.1 on 2023-02-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='created_at',
        ),
    ]
