# Generated by Django 4.1.1 on 2023-02-10 16:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_action_enabled_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, default=list, size=None),
        ),
    ]
