# Generated by Django 4.1.1 on 2023-02-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_action_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
