# Generated by Django 4.1.1 on 2023-02-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_action_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='action',
            name='enabled',
        ),
    ]
