# Generated by Django 4.1.1 on 2023-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_action_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='delay',
            field=models.FloatField(null=True),
        ),
    ]
