# Generated by Django 4.1.1 on 2023-02-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_action_created_at_remove_action_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='events',
        ),
        migrations.RemoveField(
            model_name='action',
            name='status',
        ),
        migrations.RemoveField(
            model_name='action',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='action',
            name='updated_by',
        ),
    ]
