# Generated by Django 4.1.1 on 2023-02-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_match_finished_at_alter_match_media_and_more'),
        ('api', '0026_action_created_at_action_enabled_action_events_and_more'),
    ]

    operations = [
    ]
