# Generated by Django 4.1.1 on 2023-02-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_event_delay'),
        ('api', '0027_merge_20230211_0901'),
    ]

    operations = [
    ]
