# Generated by Django 4.1.1 on 2023-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20230211_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='finished_at',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='started_at',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
