# Generated by Django 4.1.1 on 2023-02-12 20:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_0025_event_delay_0027_merge_20230211_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='finished_at',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='started_at',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
