# Generated by Django 4.1.1 on 2023-02-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_match_finished_at_alter_match_started_at'),
        ('api', '0032_action_created_at'),
    ]

    operations = [
    ]
