name: Deploy Django Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Usa la misma versión que tu proyecto

    # Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Configurar Railway CLI
    - name: Set up Railway CLI
      run: |
        curl -sSL https://raw.githubusercontent.com/railwayapp/cli/main/install.sh | sh
        railway login --token ${{ secrets.RAILWAY_SERVER }}

    # Desplegar la aplicación en Railway
    - name: Deploy to Railway
      run: railway up
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_SERVER }}

    # Aplicar migraciones
    - name: Apply migrations
      run: railway run python manage.py migrate
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_DATABSE }}
